local name = "STAFNO"

local Programming_Languages = {"lua","python","html","css","C++","C#","Kotlin","JavaScript","PhP","And More"}

local Company = "Ruthx Studios"

function best()
 if table.find(Programming_Languages,lua) then 
    return 
    "Lua"
 if not table.find(Programming_Languages,lua) then 
      return
      "py,C++"
    end
end
  
local Fav_P_Language = best()
 
 local Age = 1+2*3^3/2+2-15*-1*-1+1
  
local ForContact = "https://discord.gg/rKsGhScZ3T" or "<STAFN0\>#7121"
  
function STAFNO()
   print("My Name Is: "..name.." The Programming Languages i know: "..Programming_Languages.."I'm The Owner OF: "..Company.."Fav Language: "..Fav_P_Language.." Age: "..Age)
end

STAFNO()
